server:
  port: 8088

spring:
  application:
    name: shop_app_back_end
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD:SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 300000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: GOOGLE_CLIENT_ID
            client-secret: GOOGLE_CLIENT_SECRET
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:4200/auth/google/callback}
            scope:
              - openid
              - profile
              - email
          facebook:
            client-id: FACEBOOK_CLIENT_ID
            client-secret: FACEBOOK_CLIENT_SECRET
            redirect-uri: ${FACEBOOK_REDIRECT_URI:http://localhost:4200/auth/facebook/callback}
            scope:
              - public_profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          facebook:
            authorization-uri: https://www.facebook.com/v21.0/dialog/oauth
            token-uri: https://graph.facebook.com/v21.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v21.0/me?fields=id,name,email,picture.type(large)
            user-name-attribute: id
      resource-server:
        opaque-token:
          introspection-uri: "http://example-introspection-url.com"
          client-id: <your-client-id>
          client-secret: <your-client-secret>
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: order-processor
      auto-offset-reset: latest
      enable-auto-commit: false
      max-poll-records: 500
      fetch-max-wait: 2000
      fetch-min-size: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.type.mapping: "orderDTO:com.project.shopapp.DTO.OrderDTO"
        spring.json.value.default.type: "com.project.shopapp.DTO.OrderDTO"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      security.protocol: PLAINTEXT
    listener:
      concurrency: 5
      ack-mode: manual
      missing-topics-fatal: false

api:
  prefix: api/v1

jwt:
  expiration: 2592000
  secretKey: $(JWT_SECRET:JWT_SECRET)

payment:
  vnPay:
    url: ${PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    tmnCode: ${TMN_CODE:TMN_CODE}
    secretKey: ${SECRET_KEY:SECRET_KEY}
    returnUrl: ${RETURN_URL:http://localhost:4200/user/VNPay}
    version: ${VERSION:2.1.0}
    command: ${COMMAND:pay}
    orderType: ${ORDER_TYPE:other}